dist: trusty
sudo: required
language: minimal
addons:
  apt:
    packages:
    - qemu-utils
    - bzip2
script:
- sudo ./build-3.10-image.sh
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Ben Pye"
  - git config --local user.email "ben@curlybracket.co.uk"
  - git tag "$(cat ./version)"
deploy:
  provider: releases
  api_key:
    secure: l6HnTZamfXiMigaYuxBbbDtYoABp9G9q+Ce/2W1hMLhCAyrihnXUStjRFo942O1CwDUoe/UyGQ69scxs1sxGx4kqqmwBzGMRkfyEZEH+uEzYNvXq8nnKLg2XTWiVo2sJ9Ou6CQN4mYHvVnGY32IZQyEIj/pGEZCQignEkmxbEgl3WfUw1llycmAD6ixrzHL1SsOivKkvlaM/m9FkHpZZjIV0fryH5nnphDyx2tHERgNp2Bo9YnfeovMmKpMD+FKOaHliyoHlog6kwKDkfhErSDVLoXonsV1S64nHUvYwSDpVclxfboBTU3/iOIYBqIBrTpvxjIJZREehuE4URQ2BcKtxlwc7ifioxsKLDBCAzYlxTE92yEqDIvf94XRD+vaG8WjLwcpjlRfp7QJGr0U3OAk9yaeqQH4e8itI/mDwCydyf1cBlhC1RiiNK38tIHRNv9SoWomLL37wOnZUHXbUYNv4NDvqABke0MmhOXpIrEu+MXecoiNNDVk/zVsQFWMDtVsHMhOQgETrNo2hHqf/YFJ0gtxhMLYjwo0zA2yBg+Ih0FDTYA2ojOCM70PGxrWnQ0Z+0ECRkphWCFGN2/yj9O7x/CHcQBp/nMuTIGoFfRQOX7ywTsNL9dRm/Vfarg16CuI6M7WiV+QeajOHMaXSKDJS0Dp1EV3leEFAKAzHI8I=
  file: "*.bz2"
  file_glob: true
  skip_cleanup: true
  on:
    repo: benpye/alpine-droplet
